import assert from "node:assert/strict";
import { readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { test } from "node:test";
import { isMigrationFile, migrationName, pendingMigrations } from "./migration-plan.mjs";

const projectRoot = () => join(dirname(fileURLToPath(import.meta.url)), "..");

test("_migrations keys on basename, not path", () => {
  assert.equal(migrationName("/migrations/0002_todos.sql"), "0002_todos.sql");
  assert.equal(migrationName("migrations/0001_auth.sql"), "0001_auth.sql");
  assert.equal(migrationName("0001_auth.sql"), "0001_auth.sql");
});

test("a file already applied from another directory does not re-apply", () => {
  // Vite's glob yields absolute-ish paths while `_migrations` stores basenames.
  // Keying on the basename is what stops a re-apply after a path change.
  assert.deepEqual(pendingMigrations(["/migrations/0001_auth.sql"], ["0001_auth.sql"]), []);
});

test("pending migrations are returned in name order", () => {
  assert.deepEqual(
    pendingMigrations(
      ["/migrations/0003_c.sql", "/migrations/0001_a.sql", "/migrations/0002_b.sql"],
      ["0001_a.sql"],
    ),
    [
      { name: "0002_b.sql", path: "/migrations/0002_b.sql" },
      { name: "0003_c.sql", path: "/migrations/0003_c.sql" },
    ],
  );
});

test("non-.sql entries are dropped", () => {
  assert.equal(isMigrationFile("README.md"), false);
  assert.equal(isMigrationFile("0001_auth.sql"), true);
  assert.deepEqual(pendingMigrations(["notes", "README.md"], []), []);
});

test("this workspace's migrations are all picked up, in order", () => {
  // Auth is a first-class migration here, not an opt-in copy: the app is
  // allowlisted-editor-only, so it always needs the identity tables. 0004 is
  // generated by scripts/build-org-intake-migration.mjs and seeds the
  // organisation review queue, so it must be listed here too.
  const entries = readdirSync(join(projectRoot(), "migrations"));
  const planned = pendingMigrations(entries, []).map((m) => m.name);
  assert.deepEqual(planned, [
    "0001_auth.sql",
    "0002_contributions.sql",
    "0003_review.sql",
    "0004_organisation_candidates.sql",
    "0005_enrichment.sql",
  ]);
});

test("an applied migration drops out of the plan", () => {
  const entries = readdirSync(join(projectRoot(), "migrations"));
  const planned = pendingMigrations(entries, ["0001_auth.sql"]).map((m) => m.name);
  assert.deepEqual(planned, [
    "0002_contributions.sql",
    "0003_review.sql",
    "0004_organisation_candidates.sql",
    "0005_enrichment.sql",
  ]);
});
